import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "react-bootstrap";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="text-center mt-5">
      <Head>
        <title>Welcome to PasteBin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to PasteBin</h1>
      <p>
          This is an application for people to upload and share various snippets
        of text.
      </p>
      <Button href="/create-snippet" variant="outline-info">
        Create a Snippet
      </Button>
    </div>
  );
}
